# Vi layer PTY test suite
#
# Invoked from the root Makefile via:  make test  ->  $(MAKE) -C tests test

test:
	python3 test_vi.py

list:
	python3 test_vi.py --list

clean:
	rm -rf __pycache__

.PHONY: test list clean
